### ISSUE TITLE
I've been getting this error in the last 5 lessons, because the graphing formula has mode = 'line' as default, which isn't being accepted by plotly, so it cant show the graphs

### ISSUE THREAD

**Issue by AlludedCrabb** [learn-co-curriculum/gradient-descent#2]
ValueError: 
    Invalid value of type 'builtins.str' received for the 'mode' property of scatter
        Received value: 'line'

    The 'mode' property is a flaglist and may be specified
    as a string containing:
      - Any combination of ['lines', 'markers', 'text'] joined with '+' characters
        (e.g. 'lines+markers')
        OR exactly one of ['none'] (e.g. 'none')

**Comment by CodeShareDude** [comment]
I've been running into the same issue. I believe mode should be set to 'lines' instead of 'line'

**Comment by aviflombaum** [comment]
I have applied the fix from @CodeShareDude in https://github.com/learn-co-curriculum/gradient-descent/commit/1bc4d6ea3e6c20fa4541f8a80600946b4c24124d

**Comment by carloskruger** [comment]
I still encountered this issue. Also with 'right' for textposition
