### ISSUE TITLE
readme code confounds

### ISSUE THREAD

**Issue by annieeby** [learn-co-curriculum/gradient-descent#3]
i tried changing line and marker to lines and markers, that didn't help, my debugging skills not good enough to see how to fix your code.

from graph import trace, plot, line_function_trace

def y_actual(x, x_values, y_values):
    combined_values = list(zip(x_values, y_values))
    point_at_x = list(filter(lambda point: point[0] == x,combined_values))[0]
    return point_at_x[1]

def error_line_trace(x_values, y_values, m, b, x):
    y_hat = m*x + b
    y = y_actual(x, x_values, y_values)
    name = 'error at ' + str(x)
    error_value = y - y_hat
    return {'x': [x, x], 'y': [y, y_hat], 'mode': 'line', 'marker': {'color': 'red'}, 'name': name, 'text': [error_value], 'textposition':'right'}

def error_line_traces(x_values, y_values, m, b):
    return list(map(lambda x_value: error_line_trace(x_values, y_values, m, b, x_value), x_values))

errors = error_line_traces(budgets, revenues, 1.417, 133.33)
plot([scatter_trace, regression_trace, *errors])

**Comment by LoreDirick** [comment]
Seems like for the argument `'textposition'`, `'right'`is not a valid option. Changed to `'textposition':'top right'`. Thanks for raising the issue!
