### ISSUE TITLE
Linear equations and graphs > evaluation regression lines > gradient decent : Typo

### ISSUE THREAD

**Issue by mgavish** [learn-co-curriculum/gradient-descent#6]
under 'Updating the regression line to improve accuracy' , they start off with "Ok, so we have a regression line of  y¯=m¯x+b¯ , using bar instead of hat?  Does bar not represent an average? Unless you are using y bar to notate a closest fit value though, I think the new notation should be introduced in the ReadMe before used.

**Comment by mas16** [comment]
Hi mgavish! thanks for the note! the equation has been updated.
